# 数组操作

In [1]:
import numpy as np

## 更改形状
#### 在对数组进行操作时，为了满足格式和计算的要求通常会改变其形状。

#### numpy.ndarray.shape表示数组的维度，返回一个元组，这个元组的长度就是维度的数目，即nidm属性（秩）。

#### 【例】通过修改shape属性来改变数组的形状

In [3]:
x = np.array([1,2,3,4,5,6,7,8])
x.shape

(8,)

In [5]:
x.shape = [2,4]  # 修改shape的属性，将shape改成2行4列的二维数组
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### numpy.ndarray.flat将数组转换为一维的迭代器，可以用for访问数组每一个元素。

In [8]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
y = x.flat
y

In [16]:
for i in y:
    print(i,end = ' ')

11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 

In [17]:
y[3] = 0
print(x,end = '\n')

[[11 12 13  0 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


#### numpy.ndarray.flatten([order = 'C']) 将数组的副本转换为一维数组，并返回。
####  order：'C' --按行，'F'--按列，'A' --原顺序， 'k'--元素在内存中的出现顺序。（简记）
#### 【例】 flatten( )函数返回的是拷贝。

In [18]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = x.flatten()
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [19]:
y[3] = 0
y

array([11, 12, 13,  0, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [20]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [21]:
y = x.flatten(order = 'F')
y

array([11, 16, 21, 26, 31, 12, 17, 22, 27, 32, 13, 18, 23, 28, 33, 14, 19,
       24, 29, 34, 15, 20, 25, 30, 35])

In [23]:
y [3] = 0
y

array([11, 16, 21,  0, 31, 12, 17, 22, 27, 32, 13, 18, 23, 28, 33, 14, 19,
       24, 29, 34, 15, 20, 25, 30, 35])

In [24]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### numpy.ravel(a,order = 'C') Return a contiguous flattened array.
#### 【例】 ravel( ) 返回的是视图

In [26]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = np.ravel(x)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [27]:
y[3] = 0
x

array([[11, 12, 13,  0, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### 而 order = 'F' 则是拷贝

In [28]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = np.ravel(x,order = 'F')  # 按列转换成一维数组
y

array([11, 16, 21, 26, 31, 12, 17, 22, 27, 32, 13, 18, 23, 28, 33, 14, 19,
       24, 29, 34, 15, 20, 25, 30, 35])

In [29]:
y[3] = 0
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

#### numpy.reshape(a,newshape[ , order = 'C'])在不更改数据的情况下为数组赋予新的形状。
#### 【例】reshape( ) 函数，当参数newshape = [rows , -1]时，将根据行数自动确定列数。

In [30]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
y = np.reshape(x,[3,4])
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
y.dtype

dtype('int64')

In [33]:
y = np.reshape(x,[3,-1])
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
y = np.reshape(x,[-1,3])
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
y[0,1] = 10   # 改变x的reshape后y中的值，x对应的元素也改变
x

array([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 【例】reshape（）函数，当参数newshape = -1时，表示将数组降为！一维。

In [38]:
x = np.random.randint(12,size = [2,2,3])
x

array([[[ 5,  0,  7],
        [ 6,  8,  1]],

       [[11,  9,  5],
        [ 2,  6, 10]]])

In [39]:
y = np.reshape(x,newshape=-1)
y

array([ 5,  0,  7,  6,  8,  1, 11,  9,  5,  2,  6, 10])

## 数组转置

In [42]:
x = np.random.rand(5,5)*10  # 5*5 0-1之间的数，再*10 
x

array([[1.40057896, 8.07801757, 2.68461029, 0.04849757, 3.94735082],
       [4.18930133, 5.98245028, 0.87529998, 6.00613964, 4.3769878 ],
       [8.7060044 , 2.67114617, 6.59149845, 1.66594955, 5.84281277],
       [3.36760478, 7.31453845, 3.29807569, 0.64882688, 9.48285963],
       [1.64272356, 7.27391043, 0.28325724, 0.38363938, 5.79899309]])

In [44]:
x = np.around(x,2) 
x

array([[1.4 , 8.08, 2.68, 0.05, 3.95],
       [4.19, 5.98, 0.88, 6.01, 4.38],
       [8.71, 2.67, 6.59, 1.67, 5.84],
       [3.37, 7.31, 3.3 , 0.65, 9.48],
       [1.64, 7.27, 0.28, 0.38, 5.8 ]])

In [45]:
y = x.T
y

array([[1.4 , 4.19, 8.71, 3.37, 1.64],
       [8.08, 5.98, 2.67, 7.31, 7.27],
       [2.68, 0.88, 6.59, 3.3 , 0.28],
       [0.05, 6.01, 1.67, 0.65, 0.38],
       [3.95, 4.38, 5.84, 9.48, 5.8 ]])

In [46]:
y = np.transpose(x)
y

array([[1.4 , 4.19, 8.71, 3.37, 1.64],
       [8.08, 5.98, 2.67, 7.31, 7.27],
       [2.68, 0.88, 6.59, 3.3 , 0.28],
       [0.05, 6.01, 1.67, 0.65, 0.38],
       [3.95, 4.38, 5.84, 9.48, 5.8 ]])

## 更改维度
#### 当创建一个数组之后，还可以给增加一个维度，这在矩阵计算中经常会用到。
#### numpy.newaxis = None  None的别名，对索引数组很有用。
#### 【例】 很多工具包在进行计算时都会判断输入数据的维度是否满足要求，如果输入数据达不到指定的维度时，可以使用newaxis参数来增加一个维度。

In [48]:
x = np.array([1,2,9,4,5,6,7,8])
x.shape

(8,)

In [49]:
x

array([1, 2, 9, 4, 5, 6, 7, 8])

In [50]:
y = x[np.newaxis,:]
y

array([[1, 2, 9, 4, 5, 6, 7, 8]])

In [51]:
y.shape

(1, 8)

In [52]:
y = x[:,np.newaxis]
y.shape

(8, 1)

In [53]:
y

array([[1],
       [2],
       [9],
       [4],
       [5],
       [6],
       [7],
       [8]])

## 数组组合
#### 如果要将两份数据组合到一起，就需要拼接操作。
#### numpy.concatenate( [a1,a2,...],axis = 0,out = None )

#### 【例】连接沿现有轴的数组序列（原来x，y都是一维的，拼接后的结果也是一维的）。

In [54]:
x = np.array([1,2,3])
y = np.array([7,8,9])
np.concatenate([x,y])

array([1, 2, 3, 7, 8, 9])

In [55]:
np.concatenate([x,y],axis = 0)

array([1, 2, 3, 7, 8, 9])

#### 【例】原来x，y都是二维的，拼接后也是二维的。

In [60]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([7,8,9]).reshape(1,3)
z = np.concatenate([x,y])
z

array([[1, 2, 3],
       [7, 8, 9]])

In [57]:
z = np.concatenate([x,y],axis = 0)
z

array([[1, 2, 3],
       [7, 8, 9]])

In [61]:
z = np.concatenate([x,y],axis = 1)
z

array([[1, 2, 3, 7, 8, 9]])

#### 【例】x，y在原来的维度上进行拼接。

In [62]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
z = np.concatenate([x,y])
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
z = np.concatenate([x,y],axis = 0)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
z = np.concatenate([x,y],axis = 1)
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### numpy.stack(arrays,axis = 0,out = None) Join a sequence of arrays along a new axis.
#### 【例】沿着新的轴加入一系列数组（stack为增加维度的拼接）