## 排序、搜索和计数
### 1.排序

In [1]:
import numpy as np
np.random.seed(20101029) # 设置随机数种子，使得下次生成的随机值相同
x = np.random.rand(5,5)*10
x

array([[1.45542487, 4.12438221, 8.30274833, 7.22116923, 2.80901421],
       [0.99702118, 7.9059145 , 2.37972133, 6.04679987, 8.43310475],
       [4.18965118, 3.03574799, 2.8288833 , 6.96987966, 6.52513894],
       [9.06909529, 3.08840134, 7.44407248, 0.30115865, 3.38323311],
       [3.29700875, 7.74415971, 2.30617142, 0.51021436, 3.68571724]])

In [2]:
x = np.around(x,2)
x

array([[1.46, 4.12, 8.3 , 7.22, 2.81],
       [1.  , 7.91, 2.38, 6.05, 8.43],
       [4.19, 3.04, 2.83, 6.97, 6.53],
       [9.07, 3.09, 7.44, 0.3 , 3.38],
       [3.3 , 7.74, 2.31, 0.51, 3.69]])

In [3]:
y = np.sort(x)
y

array([[1.46, 2.81, 4.12, 7.22, 8.3 ],
       [1.  , 2.38, 6.05, 7.91, 8.43],
       [2.83, 3.04, 4.19, 6.53, 6.97],
       [0.3 , 3.09, 3.38, 7.44, 9.07],
       [0.51, 2.31, 3.3 , 3.69, 7.74]])

In [5]:
y = np.sort(x,axis=0) # axis = 0 行的方向，跨列
y

array([[1.  , 3.04, 2.31, 0.3 , 2.81],
       [1.46, 3.09, 2.38, 0.51, 3.38],
       [3.3 , 4.12, 2.83, 6.05, 3.69],
       [4.19, 7.74, 7.44, 6.97, 6.53],
       [9.07, 7.91, 8.3 , 7.22, 8.43]])

In [6]:
y = np.sort(x,axis=1)
y

array([[1.46, 2.81, 4.12, 7.22, 8.3 ],
       [1.  , 2.38, 6.05, 7.91, 8.43],
       [2.83, 3.04, 4.19, 6.53, 6.97],
       [0.3 , 3.09, 3.38, 7.44, 9.07],
       [0.51, 2.31, 3.3 , 3.69, 7.74]])

In [9]:
import numpy as np
dt = np.dtype([('name','S10'),('age',np.int)])
a = np.array([('Mike',21),('Nancy',25),('Bob',17),('Jan',27)],dtype = dt)
b = np.sort(a,order = 'name')   # 按 name列 首字母排序
b

array([(b'Bob', 17), (b'Jan', 27), (b'Mike', 21), (b'Nancy', 25)],
      dtype=[('name', 'S10'), ('age', '<i8')])

#### 【例】对数组沿给定轴执行间接排序，并使用指定排序类型返回数据的索引数据。这个索引数据用于构造排序后的数组。

In [10]:
import numpy as np
np.random.seed(20201031)
x = np.random.randint(0,10,10)
x

array([2, 0, 4, 3, 7, 7, 1, 6, 8, 0])

In [11]:
y = np.argsort(x)  # 返回排序（默认升序）后的索引数据
y

array([1, 9, 6, 0, 3, 2, 7, 4, 5, 8])

In [12]:
x[y]

array([0, 0, 1, 2, 3, 4, 6, 7, 7, 8])

In [13]:
y = np.argsort(-x)
y

array([8, 4, 5, 7, 2, 3, 0, 6, 1, 9])

In [14]:
x[y]

array([8, 7, 7, 6, 4, 3, 2, 1, 0, 0])