# 副本与视图
##### 在Numpy中，尤其是在做数组运算或数组操作时，返回结果不是数组的副本就是视图。
### 在Numpy中，所以赋值运算不会为数组和数组中的任何元素创建副本。

In [4]:
# 【例】
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
y = x
y[0] = -1
x    # x == y Numpy中，赋值操作不会为数组和数组中的任何元素创建副本。

array([-1,  2,  3,  4,  5,  6,  7,  8])

In [3]:
y

array([-1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
x = np.array([1,2,3,4,5,6,7,8])
y = x.copy()
y[0] = -1
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
y

array([-1,  2,  3,  4,  5,  6,  7,  8])

In [12]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = x
y[::2,:3:2] = -1 # 取全部的行，步长为2，即1，3，5...行；列取前三列， 步长也为2，即 第1，3（索引0，2）列
x

array([[-1, 12, -1, 14, 15],
       [16, 17, 18, 19, 20],
       [-1, 22, -1, 24, 25],
       [26, 27, 28, 29, 30],
       [-1, 32, -1, 34, 35]])

In [13]:
y

array([[-1, 12, -1, 14, 15],
       [16, 17, 18, 19, 20],
       [-1, 22, -1, 24, 25],
       [26, 27, 28, 29, 30],
       [-1, 32, -1, 34, 35]])

In [15]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = x.copy()
y[::2,:3:2] = -1
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [16]:
y

array([[-1, 12, -1, 14, 15],
       [16, 17, 18, 19, 20],
       [-1, 22, -1, 24, 25],
       [26, 27, 28, 29, 30],
       [-1, 32, -1, 34, 35]])

# 索引和切片
#### 数组索引机制值的是用方括号（ [ ] ）加序号的形式引用单个数组元素，它的用处很多，比如抽取元素，选取数组的几个元素，甚至为其赋一个新值。

## 整数索引
#### 【例】要获取数组的单个元素，指定元素的索引即可。

In [17]:
x = np.array([1,2,3,4,5,6,7,8])
x[2]

3

In [18]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x[2]

array([21, 22, 23, 24, 25])

In [19]:
x[2][1]

22

In [20]:
x[2,1]

22

## 切片索引
#### 切片操作是值抽取数组的一部分元素生成新数组。对python列表进行切片操作得到的数组是原数组的副本，而对Numpy数据进行切片操作得到的数组则是指向相同缓冲区的视图。

#### 如果想抽取（或查看）数组的一部分，必须使用切片语法。也就是，把几个用冒号（[start:stop:step]）隔开的数字置于方括号内。

#### 了解不明确指明起始和结束位置的情况。如，省去第一个数字，numpy会认为第一个数字是0；如，省去第二个数字，numpy则会认为第二个数字是数组的最大索引值；如，省去最后一个数字，它将会被理解为1，也就是抽取所有的元素而不再考虑间隔。

#### 【例】对一维数组的切片

In [21]:
x = np.array([1,2,3,4,5,6,7,8])
x[0:2]

array([1, 2])

In [22]:
# 用下标0-5，以2为步长选取数据
x[1:5:2]

array([2, 4])

In [23]:
x[2:]

array([3, 4, 5, 6, 7, 8])

In [24]:
x[:2]

array([1, 2])

In [25]:
x[-2:] #最后两个

array([7, 8])

In [26]:
x[:-2]  #最后俩不要

array([1, 2, 3, 4, 5, 6])

In [27]:
x[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
# 利用负数下标翻转数组
x[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

#### 【例】对二维数组切片

In [29]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x[0:2]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
x[1:5:2]

array([[16, 17, 18, 19, 20],
       [26, 27, 28, 29, 30]])

In [31]:
x[2:]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
x[:2]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
x[-2:]

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [34]:
x[:-2]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
x[:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [36]:
x[2,:] # 行列用，区分

array([21, 22, 23, 24, 25])

In [37]:
x[:,2]

array([13, 18, 23, 28, 33])

In [38]:
x[0,1:4]

array([12, 13, 14])

In [39]:
x[1:4,0]

array([16, 21, 26])

In [40]:
x[1:3,2:4]

array([[18, 19],
       [23, 24]])

In [41]:
x[:,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [42]:
x[::2,::2]

array([[11, 13, 15],
       [21, 23, 25],
       [31, 33, 35]])

In [43]:
x[::-1,:]

array([[31, 32, 33, 34, 35],
       [26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15]])

In [44]:
x[:,::-1]

array([[15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21],
       [30, 29, 28, 27, 26],
       [35, 34, 33, 32, 31]])

【例】

In [45]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [46]:
x[0::2,1::3] = 0
x

array([[11,  0, 13, 14,  0],
       [16, 17, 18, 19, 20],
       [21,  0, 23, 24,  0],
       [26, 27, 28, 29, 30],
       [31,  0, 33, 34,  0]])

## dots 索引
#### Numpy 允许使用...表示足够多的冒号来构建完整的索引列表。
### 比如，如果x是5维数组：
#### x[ 1 , 2 , . . . ]等于x[ 1 , 2, : , : , : ]
#### x[ . . . ,3 ]等于x[ : , : , : ,: , 3 ]
#### x[ 4, . . . ,5 , : ] 等于[ 4 , : , : , 5, : ]

#### 【例】

In [58]:
x = np.random.randint(1,100,[2,2,3]) # 生成[1,100]的整数， [2,2,3]  2块 2行3列
x

array([[[ 9, 45, 24],
        [ 6,  6, 48]],

       [[70, 87, 41],
        [14, 54, 38]]])

In [59]:
x[1,...]

array([[70, 87, 41],
       [14, 54, 38]])

In [60]:
x[...,2]

array([[24, 48],
       [41, 38]])

## 整数数组索引
#### 【例】方括号内传入多个索引值，可以同时选择多个元素。

In [62]:
x = np.array([1,2,3,4,5,6,7,8])
r = [0,1,2]
x[[0,1,2]]

array([1, 2, 3])

In [63]:
x[r]

array([1, 2, 3])

In [64]:
r = [0,1,-1]
x[r]

array([1, 2, 8])

In [65]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
r = [0,1,2]
x[r]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
r = [0,1,-1]
x[r]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35]])

In [67]:
r = [0,1,2]
c = [2,3,4]
x[r,c]    # 取第1行的第3个，第2行的第4个，第3行的第5个

array([13, 19, 25])

In [69]:
x = np.array([1,2,3,4,5,6,7,8])
r = np.array([[0,1],[3,4]])
x[r]

array([[1, 2],
       [4, 5]])

In [70]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x[r]

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]]])

In [73]:
# 获取 5*5数组中四个角的元素
# 行索引是[0,0]和[4,4]，而列索引是[0,4]和[0,4]
r = np.array([[0,0],[4,4]])
c = np.array([[0,4],[0,4]])
x[r,c]

array([[11, 15],
       [31, 35]])

#### 【例】 可以借助切片：与整数数组组合

In [74]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x[0:3,[1,2,2]]

array([[12, 13, 13],
       [17, 18, 18],
       [22, 23, 23]])

In [75]:
#【例】
x = np.array([1,2,3,4,5,6,7,8])
r = [0,1,2]
np.take(x,r)

array([1, 2, 3])

In [76]:
r = [0,1,-1]
np.take(x,r)

array([1, 2, 8])

In [77]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
r = [0,1,2]
np.take(x,r)

array([11, 12, 13])

In [78]:
np.take(x,r,axis = 0)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
r = [0,1,-1]
np.take(x,r,axis = 0)

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35]])

In [80]:
r = [0,1,2]
c = [2,3,4]
np.take(x,[r,c])

array([[11, 12, 13],
       [13, 14, 15]])

### 注意

In [81]:
a = np.array([[1,2],[3,4],[5,6]])
b = a[0:1,0:1]
b

array([[1]])

In [82]:
b[0,0] = 2
b

array([[2]])

In [83]:
a[0,0]

2

In [86]:
a[0,0] == b

array([[ True]])

In [95]:
a = np.array([[1,2],[3,4],[5,6]])
b = a[0,0]
b

1

In [96]:
b = 2

In [91]:
b

2

In [97]:
a[0,0]

1

In [98]:
a[0,0] == b

False

## 布尔索引