# 数学函数
## 向量化和广播

#### 【例】 二维数组加一维数组

In [2]:
import numpy as np
x = np.arange(4)
y = np.ones((3,4))
x

array([0, 1, 2, 3])

In [3]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
x.shape

(4,)

In [5]:
y.shape

(3, 4)

In [6]:
x+y  # 广播~

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [7]:
(x+y).shape

(3, 4)

##### 【例】两个数组均需要广播

In [8]:
x = np.arange(4).reshape(4,1)
x

array([[0],
       [1],
       [2],
       [3]])

In [10]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [11]:
x.shape

(4, 1)

In [12]:
y.shape

(5,)

In [13]:
x+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [14]:
(x+y).shape

(4, 5)

In [15]:
x = np.array([0.0,10.0,20.0,30.0])
y = np.array([1.0,2.0,3.0])
x[:,np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [16]:
x[:,np.newaxis] + y

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

#### 【例】不匹配报错的例子

In [1]:
import numpy as np
x = np.arange(4)
y = np.ones(5)
x

array([0, 1, 2, 3])

In [2]:
y

array([1., 1., 1., 1., 1.])

In [4]:
x.shape

(4,)

In [5]:
y.shape

(5,)

In [6]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

## 数学函数
### 算数运算
#### numpy.add
#### numpy.subtract
#### numpy.multiply
#### numpy.divide
#### numpy.floor_divide
#### numpy.power

#### 在 numpy 中对以上函数进行了运算符的重载，且运算符为 元素级。也就是说，它们只用于位置相同的元素之间，所得到的运算结果组成一个新的数组。

 #### 【例】注意numpy的广播规则。

In [7]:
x = np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
y = x+1
y

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.add(x,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = x - 1
y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.subtract(x,1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
y = x*2
y

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
np.multiply(x,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [14]:
y = x/2
y

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [15]:
np.divide(x,2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [16]:
y = x//2   # 下取整
y

array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int32)

In [17]:
np.floor_divide(x,2)

array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int32)

In [18]:
y = x**2
y

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [19]:
np.power(x,2)

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

#### 【例】注意numpy的广播规则。

In [20]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
y = x + 1
y

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36]])

In [21]:
np.add(x,1)

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36]])

In [23]:
y = x - 1
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [24]:
np.subtract(x,1)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [25]:
y = x*2
y

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [26]:
np.multiply(x,2)

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [27]:
y = x/2
y

array([[ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5],
       [13. , 13.5, 14. , 14.5, 15. ],
       [15.5, 16. , 16.5, 17. , 17.5]])

In [28]:
np.divide(x,2)

array([[ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5],
       [13. , 13.5, 14. , 14.5, 15. ],
       [15.5, 16. , 16.5, 17. , 17.5]])

In [29]:
y = x//2
y

array([[ 5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12],
       [13, 13, 14, 14, 15],
       [15, 16, 16, 17, 17]], dtype=int32)

In [30]:
np.floor_divide(x,2)

array([[ 5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12],
       [13, 13, 14, 14, 15],
       [15, 16, 16, 17, 17]], dtype=int32)

In [31]:
y = x**2
y

array([[ 121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225]], dtype=int32)