# 逻辑函数
## 真值测试
### numpy.all
### numpy.any
#### numpy.all(a,axis = None,out = None,keepdims = np._NoValue)  Test whether all array elements along a given axis evaluate to True.
#### numpy.any(a,axis = None,out = None,keepdims = np._NoValue)  Test whether any array elements along a given axis evaluates to True.

In [2]:
import numpy as np
a = np.array([0,4,5])
b = a.copy()
np.all(a == b)

True

In [3]:
np.any(a ==b )

True

In [4]:
b[0] = 1
b

array([1, 4, 5])

In [5]:
np.all(a == b)

False

In [6]:
np.any(a == b)

True

In [7]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.all(a,axis = 0)

array([False, False, False])

In [10]:
np.any(a,axis = 0)

array([ True,  True,  True])

## 数组内容
### numpy.isnan
#### numpy.isnan（x,*args,**kwargs） Test element-wise for NaN and return result as a boolean array.
#### 【例】

In [11]:
a = np.array([1,2,np.nan])
np.isnan(a)

array([False, False,  True])

## 逻辑运算
### numpy.logical_not
### numpy.logical_and
### numpy.logical_or
### numpy.logical_xor

#### 【例】计算非x元素的真值。

In [15]:
np.logical_not(3)  # 非真

False

In [13]:
np.logical_not(0)

True

In [14]:
np.logical_not([True,False,1,0])

array([False,  True, False,  True])

In [16]:
x = np.arange(5)
np.logical_not(x)

array([ True, False, False, False, False])

#### 【例】 计算x1 AND x2 元素的真值。

In [17]:
np.logical_and(True,False)   # logical_and 都为真返True  一个为False则返回False

False

In [18]:
np.logical_and(1,2)

True

In [19]:
np.logical_and([True,False],[True,False])

array([ True, False])

In [20]:
x

array([0, 1, 2, 3, 4])

In [21]:
np.logical_and(x>1,x<4)

array([False, False,  True,  True, False])

#### 【例】逐元素计算x1 OR x2的真值。

In [23]:
np.logical_or(True,False) # logical_or 一真即为真

True

In [24]:
np.logical_or(False,False)

False

In [25]:
np.logical_or([True,False],[False,False])

array([ True, False])

In [26]:
x

array([0, 1, 2, 3, 4])

In [27]:
np.logical_or(x<1,x>3)

array([ True, False, False, False,  True])

#### 【例】计算x1 XOR x2的真值，按元素计算。

In [28]:
np.logical_xor(True,False)

True

In [30]:
np.logical_xor([True,True,False,False],[True,False,True,False])

array([False,  True,  True, False])

In [31]:
np.logical_xor(x<1,x>3)

array([ True, False, False, False,  True])

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.logical_xor(0,np.eye(2))

array([[ True, False],
       [False,  True]])

## 对照
### numpy.greater   Return the truth value of (x1 > x2)
### numpy.greater_equal      (x1>= x2)
### numpy.equal                    (x1 == x2)
### numpy.not_equal       (x1!= x2)
### numpy.less              (x1 < x2)
### numpy.less_equal    (x1<= x2)

#### 【例】 numpy对以上对照函数进行了运算符的重载。

In [35]:
x = np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
x > 2

array([False, False,  True,  True,  True,  True,  True,  True])

In [37]:
np.greater(x,2)

array([False, False,  True,  True,  True,  True,  True,  True])

In [39]:
x >= 2

array([False,  True,  True,  True,  True,  True,  True,  True])

In [40]:
np.greater_equal(x,2)

array([False,  True,  True,  True,  True,  True,  True,  True])

In [41]:
x == 2

array([False,  True, False, False, False, False, False, False])

In [42]:
np.equal(x,2)

array([False,  True, False, False, False, False, False, False])

In [43]:
x != 2

array([ True, False,  True,  True,  True,  True,  True,  True])

In [44]:
np.not_equal(x,2)

array([ True, False,  True,  True,  True,  True,  True,  True])

In [45]:
x <= 2

array([ True,  True, False, False, False, False, False, False])

In [46]:
np.less_equal(x,2)

array([ True,  True, False, False, False, False, False, False])

In [47]:
x < 2

array([ True, False, False, False, False, False, False, False])

In [48]:
np.less(x,2)

array([ True, False, False, False, False, False, False, False])

In [49]:
x = np.array([[11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,34,25],
              [26,27,28,29,30],
              [31,32,33,34,35]])
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 34, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [50]:
x > 20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [51]:
np.greater(x,20)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

#### 【例】

In [52]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 34, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [53]:
y = np.random.randint(10,40,[5,5])  # 生成[10,40]之间的5*5的矩阵
y

array([[26, 12, 25, 36, 37],
       [39, 34, 14, 19, 20],
       [24, 35, 29, 34, 27],
       [10, 38, 34, 31, 18],
       [32, 20, 17, 30, 26]])

In [54]:
x > y

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True,  True,  True,  True]])

In [55]:
np.greater(x,y)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True,  True,  True,  True]])

#### 【例】注意numpy的广播规则

In [56]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 34, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [57]:
y = np.random.randint(10,50,5)
y

array([12, 30, 19, 18, 41])

In [58]:
x > y  # x的每一行的值与y的进行比较

array([[False, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True,  True, False]])

### numpy.isclose
### numpy.allclose